# Generated by Django 5.1.3 on 2024-11-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("model", models.CharField(max_length=250)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Luxury", "Luxury"),
                            ("Business", "Business"),
                            ("Economy", "Economy"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("features", models.JSONField(blank=True, null=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="how many weights the car can carry"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Main image for the vehicle",
                        upload_to="vehicles_images/",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="daily_price for the vehicle",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="vehicleimage",
            name="caption",
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_images",
                to="vehicle.vehicle",
            ),
        ),
        migrations.DeleteModel(
            name="Vehicles",
        ),
    ]
