# Generated by Django 5.1.3 on 2024-11-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_vehicle_remove_vehicleimage_caption_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="image",
            new_name="thumbnail",
        ),
    ]
