# Generated by Django 5.1.3 on 2024-11-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
