# Generated by Django 5.1.3 on 2024-11-30 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle", "0003_rename_image_vehicle_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=500)),
                ("dropoff_location", models.CharField(max_length=500)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("One-Way", "One-Way"), ("Round-Trip", "Round-Trip")],
                        default="One-Way",
                        max_length=15,
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("trip_duration", models.PositiveIntegerField()),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.vehicle",
                    ),
                ),
            ],
        ),
    ]
